echo "test_colors.py"
python test_colors.py
echo "test_constants.py"
python test_constants.py
echo "test_plot.py"
python test_plot.py
echo "test_process.py"
python test_process.py
echo "test_simulate.py"
python test_simulate.py
echo "test_sitie.py"
python test_sitie.py
echo "test_colorwheel_location.py"
python "test_colorwheel_location.py"
